### ISSUE TITLE
Build fails on Python 3.4 on Windows 7 x64

### ISSUE THREAD

**Issue by jafrey** [ifduyue/python-xxhash#5] opened 2015-02-19 20:28 UTC
Trying to build on Windows 7 x64 with Python 3 I get the following error:

    python-xxhash.c
    python-xxhash.c(363) : error C2099: initializer is not a constant
    python-xxhash.c(687) : error C2099: initializer is not a constant
    error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio 10.0\\VC\\Bin\\amd64\\cl.exe' failed with exit status 2

**Comment by ifduyue** [comment] 2015-02-20 05:10
Thanks for reporting. I will look into this a few days later. It's Chinese Spring Festeval here.

**Comment by ifduyue** [comment] 2015-02-20 05:14
A google search leads me here: https://docs.python.org/3.1/extending/windows.html
Paragraphs before Section 4.2. described how to solve this.

**Comment by ifduyue** [comment] 2015-02-20 05:39
Here is a possible fix https://github.com/ifduyue/python-xxhash/tree/issue-5, not tested yet.

**Comment by ifduyue** [comment] 2015-08-05 03:03
I'm going to close this issue. Feel free to reopen it if the problem isn't solved.

**Closed by ifduyue** 2015-08-05 03:03 UTC
